### PR TITLE
Add UI mockup and update docs

### LINKED ISSUE #10: Add UI mockup and AB3 credits
AB3 Credits:
> This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).

### PR DESCRIPTION
**Pull request by shenyih0ng**
Closes #10

## UI Mockup
Generated by Figma, feel free to suggest changes :)

Figma Link: https://www.figma.com/file/32QS6cePQW51uAcCy8qNeG/CLIMods-UI-Mockup?node-id=0%3A1

### CODE REVIEW

**Comment by huzaifa1712** [comment]
Should we have space below the command input for displaying error messages like in AB3? Rest LGTM, very nice

**Comment by shenyih0ng** [comment]
> Should we have space below the command input for displaying error messages like in AB3? Rest LGTM, very nice

oh yes i missed that out! let me go add it

**Comment by SeekSaveServe** [comment]
I made a one dark mode and shifted the order of "my mods" in increasing order of the day of the week

**Comment by shenyih0ng** [comment]
> I made a one dark mode and shifted the order of "my mods" in increasing order of the day of the week. Its in the same figma :D
> 
> Screenshot_10

should we just stick to one mode? Feel like toggling dark-light mode is a nice to have not very crucial, but if we were to put both in our docs we might need to implement the toggle. I'm leaning towards putting the dark mode as our default, what do your think?

**Comment by zupey** [comment]
I agree that we should only focus on one mode and I would prefer dark mode.

**Pull request merged**
