### PR TITLE
Change CSS styling and add new Module Card

### PR DESCRIPTION
**Pull request by SeekSaveServe**
UI Changes:
1. New ModuleCard class
2. CSS and style changes
3. Logo changed to a cli logo 

To Test:
1. Run launcher in *java/seedu/address/ui/module/Launcher.java*
2. There will be an error pop-up since the logic manager is left as null (this is surely a feature - being able to test both the error box's UI and the main UI without doing any additional work 🔥 )

To do:
1. Add my module panel
2. Make module card for the panel

Preview
*With decorator*
Screenshot_7

*Without decorator*

Screenshot_6

### CODE REVIEW

**Comment by shenyih0ng** [comment]
@SeekSaveServe might want to remove all the `.class` files

**Comment by zupey** [comment]
can update `.gitignore` to prevent git from tracking the class files.

I'm not sure why your .class files are in the bin folder, its stored in `/build` on my machine, so its already in `.gitignore`.

**Comment by misterpuffin** [comment]
can teach me how do css

**Comment by shenyih0ng** [comment]
> @SeekSaveServe can update `.gitignore` to prevent git from tracking the class files.
> 
> I'm not sure why your .class files are in the bin folder, its stored in `/build` on my machine, so its already in `.gitignore`.

@SeekSaveServe putting it in `gitignore` wont alter ur past commits, you will need to rebase/remove the `.class` files from commit history

**Comment by zupey** [comment]
I tested the module on my computer and works fine. :smile:
But there were some checkstyle violations.  Remember to setup checkstyle and ensure no errors before merging to main

**Pull request closed without merging**
